CREATE TABLE TB_PUB (
    PUB_NO          CHAR(6)         CONSTRAINT PK_PUB_NO        PRIMARY KEY
    , PUB_NAME      VARCHAR2(20)    CONSTRAINT PUB_NAME         NOT NULL
    , PHONE         VARCHAR2(20)
    , DELYN         CHAR(1)         DEFAULT 'N'
                                    CONSTRAINT PUB_DELYN        CHECK (DELYN IN ('Y','N'))
    , REGDATE       DATE            DEFAULT SYSDATE
                                    CONSTRAINT PUB_REGDATE      NOT NULL
);

INSERT INTO TB_PUB  VALUES ('P00001','출판사1','000-0000-0001','N',SYSDATE);
INSERT INTO TB_PUB  VALUES ('P00002','출판사2','000-0000-0002','N',SYSDATE);
INSERT INTO TB_PUB  VALUES ('P00003','출판사3','000-0000-0003','N',SYSDATE);
INSERT INTO TB_PUB VALUES ('P00004', '문학동네', '02-222-3333', DEFAULT, DEFAULT);
INSERT INTO TB_PUB (PUB_NO, PUB_NAME) VALUES ('P00005', '한빛미디어');
INSERT INTO TB_PUB (PUB_NO, PUB_NAME, PHONE) VALUES ('P00006', '길벗', '031-222-3333');

CREATE SEQUENCE SEQ_TB_PUB;

COMMENT ON TABLE TB_PUB IS '출판사';

COMMENT ON COLUMN TB_PUB.PUB_NO     IS '출판사 번호';
COMMENT ON COLUMN TB_PUB.PUB_NAME   IS '출판사 이름';
COMMENT ON COLUMN TB_PUB.PHONE      IS '출판사 전화번호';
COMMENT ON COLUMN TB_PUB.DELYN      IS '삭제여부';
COMMENT ON COLUMN TB_PUB.REGDATE    IS '등록일';

CREATE TABLE TB_BOOK (
    BOOK_NO         CHAR(6)         CONSTRAINT PK_BOOK_NO           PRIMARY KEY
    , TITLE         VARCHAR2(100)   CONSTRAINT TITLE                NOT NULL
    , AUTHOR        VARCHAR2(20)    CONSTRAINT BOOK_AUTHOR          NOT NULL
    , PRICE         NUMBER
    , PUB_NO        CHAR(6)         CONSTRAINT FK_PUB_NO            REFERENCES TB_PUB (PUB_NO)
                                    ON DELETE CASCADE
    , RENTYN        CHAR(1)         DEFAULT 'N'
                                    CONSTRAINT BOOK_RENTYN          CHECK (RENTYN IN ('Y','N'))
    , DELYN         CHAR(1)         DEFAULT 'N'
                                    CONSTRAINT BOOK_DELYN           CHECK (DELYN IN ('Y','N'))
    , REGDATE       DATE            DEFAULT SYSDATE
                                    CONSTRAINT BOOK_REGDATE         NOT NULL
);

CREATE SEQUENCE SEQ_TB_BOOK;

COMMENT ON TABLE TB_BOOK IS '책';

COMMENT ON COLUMN TB_BOOK.BOOK_NO   IS '책 번호';
COMMENT ON COLUMN TB_BOOK.TITLE     IS '책 이름';
COMMENT ON COLUMN TB_BOOK.AUTHOR    IS '작가명';
COMMENT ON COLUMN TB_BOOK.PRICE     IS '가격';
COMMENT ON COLUMN TB_BOOK.PUB_NO    IS '출판사 번호(F)';
COMMENT ON COLUMN TB_BOOK.RENTYN    IS '대여여부 Y : 대여가능 / N : 대여불가';
COMMENT ON COLUMN TB_BOOK.DELYN     IS '삭제여부';
COMMENT ON COLUMN TB_BOOK.REGDATE   IS '대여일자';

INSERT INTO TB_BOOK VALUES ('B00001', '타이틀1', '작가1', '10000', 'P00001', 'N', 'N', SYSDATE);
INSERT INTO TB_BOOK VALUES ('B00002', '타이틀2', '작가2', '15000', 'P00001', 'N', 'N', SYSDATE);
INSERT INTO TB_BOOK VALUES ('B00003', '타이틀3', '작가3', '20000', 'P00002', 'N', 'N', SYSDATE);
INSERT INTO TB_BOOK VALUES ('B00004', '타이틀4', '작가4', '30000', 'P00003', 'N', 'N', SYSDATE);
INSERT INTO TB_BOOK VALUES ('B00005', '타이틀5', '작가5', '25000', 'P00002', 'N', 'N', SYSDATE);

CREATE TABLE TB_MEMBER(
    MEM_NO      CHAR(6)             CONSTRAINT PK_MEM_NO        PRIMARY KEY
    , ID        VARCHAR2(20)        CONSTRAINT MEMBER_ID        UNIQUE
    , PW        VARCHAR2(20)        CONSTRAINT MEMBER_PW        NOT NULL
    , NAME      VARCHAR2(20)        CONSTRAINT MEMBER_NAME      NOT NULL
    , GENDER    CHAR(1)             CONSTRAINT MEMBER_GENDER    NOT NULL
                                    CHECK (GENDER IN ('M','F'))
    , ADDR      VARCHAR2(100)
    , PHONE     VARCHAR2(20)
    , DELYN     CHAR(1)             DEFAULT 'N'
                                    CONSTRAINT MEMBER_DELYN     CHECK (DELYN IN('Y','N'))
    , REGDATE   DATE                DEFAULT SYSDATE
                                    CONSTRAINT MEMBER_REGDATE   NOT NULL
);

CREATE SEQUENCE SEQ_TB_MEM;

COMMENT ON TABLE TB_MEMBER IS '사용자';

COMMENT ON COLUMN TB_MEMBER.MEM_NO  IS '사용자 번호';
COMMENT ON COLUMN TB_MEMBER.ID      IS '아이디';
COMMENT ON COLUMN TB_MEMBER.PW      IS '패스워드';
COMMENT ON COLUMN TB_MEMBER.NAME    IS '사용자 이름';
COMMENT ON COLUMN TB_MEMBER.GENDER  IS '사용자 성별';
COMMENT ON COLUMN TB_MEMBER.ADDR    IS '사용자 주소';
COMMENT ON COLUMN TB_MEMBER.PHONE   IS '전화번호';
COMMENT ON COLUMN TB_MEMBER.DELYN   IS '삭제여부';
COMMENT ON COLUMN TB_MEMBER.REGDATE IS '가입일';

INSERT INTO TB_MEMBER  (MEM_NO, ID, PW, NAME, GENDER, REGDATE)
                VALUES ('M00001', 'ID01', 'PW01', 'NAME01', 'M', SYSDATE);
INSERT INTO TB_MEMBER  (MEM_NO, ID, PW, NAME, GENDER, REGDATE)
                VALUES ('M00002', 'ID02', 'PW02', 'NAME02', 'F', SYSDATE);
INSERT INTO TB_MEMBER  (MEM_NO, ID, PW, NAME, GENDER, REGDATE)
                VALUES ('M00003', 'ID03', 'PW03', 'NAME03', 'M', SYSDATE);
INSERT INTO TB_MEMBER  (MEM_NO, ID, PW, NAME, GENDER, REGDATE)
                VALUES ('M00004', 'ID04', 'PW04', '박서현', 'F', SYSDATE);
INSERT INTO TB_MEMBER  (MEM_NO, ID, PW, NAME, GENDER, REGDATE)
                VALUES ('M00005', 'ID05', 'PW05', '지디', 'M', SYSDATE);
INSERT INTO TB_MEMBER  (MEM_NO, ID, PW, NAME, GENDER, REGDATE)
                VALUES ('M00006', 'ID06', 'PW06', '홍형경', 'F', SYSDATE);
INSERT INTO TB_MEMBER  (MEM_NO, ID, PW, NAME, GENDER, REGDATE)
                VALUES ('M00007', 'ID07', 'PW07', '아몰랑', 'F', SYSDATE);
INSERT INTO TB_MEMBER  (MEM_NO, ID, PW, NAME, GENDER, REGDATE)
                VALUES ('M00008', 'ID08', 'PW08', '오늘도', 'M', SYSDATE);

CREATE TABLE TB_RENT (
    RENT_NO         CHAR(6)     CONSTRAINT PK_RENT_NO           PRIMARY KEY
    , MEM_NO        CHAR(6)     CONSTRAINT FK_MEM_NO
                                REFERENCES TB_MEMBER (MEM_NO)
    , BOOK_NO       CHAR(6)     CONSTRAINT FK_BOOK_NO
                                REFERENCES TB_BOOK (BOOK_NO)
    , RENT_DATE     DATE        DEFAULT SYSDATE
    , RETURN_DATE   DATE
);

CREATE SEQUENCE SEQ_TB_RENT;

COMMENT ON TABLE TB_RENT IS '대여';

COMMENT ON COLUMN TB_RENT.RENT_NO  IS '대여번호';
COMMENT ON COLUMN TB_RENT.MEM_NO  IS '사용자번호';
COMMENT ON COLUMN TB_RENT.BOOK_NO  IS '도서번호';
COMMENT ON COLUMN TB_RENT.RENT_DATE  IS '대여일자';
COMMENT ON COLUMN TB_RENT.RETURN_DATE  IS '반납일자';